on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  AWS_S3_BUCKET: fpr-frontend20230504022823432400000002
  AWS_CF_DIST_ID: E43J9DTOLL58U

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sync cacheable files with S3 bucket
        run: aws s3 sync ./dist s3://${{ env.AWS_S3_BUCKET }} --cache-control 'max-age=31536000' --exclude "*.html"

      - name: Sync non cacheable files with S3 bucket
        run: aws s3 sync ./dist s3://${{ env.AWS_S3_BUCKET }} --cache-control 'no-cache'

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CF_DIST_ID }} --paths "/*"
